# /// script
# requires-python = ">=3.11"
# dependencies = ["httpx>=0.27"]
# ///
"""Render Formula/freebox-cli.rb for KevinGallaccio/homebrew-tap.

Fetches the release's sdist URL + sha256 from PyPI and fills the formula
template. The formula pip-installs `freebox-cli[mcp]==<version>` into a brew-managed
virtualenv rather than declaring every transitive dependency as a `resource`:
the tree includes Rust (pydantic-core, rpds-py) and Cython (zeroconf)
extensions, so a hermetic from-source formula would drag a rust toolchain and
minutes of compiling into every user install. Wheels from PyPI are the same
artifacts `uvx --from freebox-cli fbx` users run.

Usage: uv run scripts/generate_brew_formula.py --version 0.6.0 --out Formula/freebox-cli.rb
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import httpx

TEMPLATE = '''\
# Autogenerated by scripts/generate_brew_formula.py in KevinGallaccio/freebox-cli
# (release workflow). Do not edit by hand — changes are overwritten on the
# next release.
class FreeboxCli < Formula
  include Language::Python::Virtualenv

  desc "Freebox Ultra CLI — the box, the network, and the VMs, from the terminal"
  homepage "https://github.com/KevinGallaccio/freebox-cli"
  url "{sdist_url}"
  sha256 "{sdist_sha256}"
  license "MIT"

  depends_on "python@{python}"

  def install
    virtualenv_create(libexec, "python{python}")
    # Install the pinned release from PyPI with normal pip resolution so
    # compiled dependencies (pydantic-core, zeroconf, rpds-py) come as
    # wheels instead of multi-minute source builds needing a rust toolchain.
    # (Verified: pip reaches PyPI inside brew's build sandbox — the no-network
    # rule is homebrew-core policy, not a mechanical restriction.)
    # NB: virtualenv_create makes the venv --without-pip; pip is reachable
    # only as a module through the brewed python's site-packages.
    system libexec/"bin/python", "-m", "pip", "install", "freebox-cli[mcp]==#{{version}}"
    bin.install_symlink libexec/"bin/fbx"
  end

  test do
    # --version prints to stderr (stdout is reserved for data).
    assert_match "fbx #{{version}}", shell_output("#{{bin}}/fbx --version 2>&1")
  end
end
'''


def sdist_of(version: str, *, retries: int = 30, delay: float = 10.0) -> tuple[str, str]:
    """URL + sha256 of the freebox-cli sdist on PyPI, waiting out index propagation."""
    url = f"https://pypi.org/pypi/freebox-cli/{version}/json"
    for attempt in range(retries):
        resp = httpx.get(url, follow_redirects=True)
        if resp.status_code == 200:
            for file in resp.json()["urls"]:
                if file["packagetype"] == "sdist":
                    return file["url"], file["digests"]["sha256"]
            sys.exit(f"freebox-cli {version} is on PyPI but has no sdist")
        if attempt < retries - 1:
            print(f"freebox-cli {version} not on PyPI yet (HTTP {resp.status_code}); retrying…")
            time.sleep(delay)
    sys.exit(f"gave up waiting for freebox-cli {version} on PyPI")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--version", required=True, help="freebox-cli release version (no leading v)"
    )
    parser.add_argument("--out", required=True, type=Path, help="path to write freebox-cli.rb")
    parser.add_argument("--python", default="3.14", help="brew python@X.Y the venv uses")
    args = parser.parse_args()

    sdist_url, sdist_sha256 = sdist_of(args.version)
    formula = TEMPLATE.format(sdist_url=sdist_url, sdist_sha256=sdist_sha256, python=args.python)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(formula)
    print(f"wrote {args.out} for freebox-cli {args.version}")


if __name__ == "__main__":
    main()
